# Thinkenterprise Properties 
thinkenterprise:
  exception:
    test:
      enabled: false
      
# GraphQL Tools and Servlet Configuration  
graphql:
  extended-scalars: Date
  tools:
    schemaLocationPattern: "**/*.graphql"
  servlet:
    mapping: /graphql
    enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
    cors-enabled: true
    cors:
      allowed-origins: http://airline.com
    maxQueryDepth: 100
    maxQueryComplexity: 100
    exception-handlers-enabled: true 
  playground:
    enabled: true
    
## H2 & Data Source Configuration 
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:airlinedb;DB_CLOSE_ON_EXIT=FALSE 
  profiles:
    active: noSecurity
  security:
    oauth2:
      resourceserver:
        jwt: 
          public-key-location: public-key.txt

## Log GraphQL Debug Information for better understanding
logging:
  level:
    '[graphql]': debug
  
## GraphQL Port Configuration 
server: 
  port: 4000
  ssl: 
    key-store-type: PKCS12
    key-store: classpath:graphql.p12
    key-store-password: graphql
    key-alias: graphql
    enabled: false