
graphql:
  extended-scalars: Date
  tools:
    schemaLocationPattern: "**/*.graphql"
  servlet:
    mapping: /graphql
    enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
  playground:
    enabled: true
    
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:airlinedb;DB_CLOSE_ON_EXIT=FALSE 

logging:
  level:
    '[graphql]': debug
  
server: 
  port: 4000
  ssl: 
    key-store-type: PKCS12
    key-store: classpath:graphql.p12
    key-store-password: graphql
    key-alias: graphql
    enabled: true
    